from comprehensive_address_test.comprehensive_address_test import comprehensive_address_test
from access_type_test.access_type_test import access_type_test
from multi_bank_test.multi_bank_test import multi_bank_test
